viewpoints:
  - x: 1.5
    y: 0.5
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 1.0
    qw: 0.0
  - x: 0.5
    y: 0.75
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 0.3826834
    qw: 0.9238795
  - x: 0.5
    y: 3.25
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 0.3826834
    qw: 0.9238795
  - x: 1.5
    y: 3.5
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 1.0
